/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 satellite.gltf --types 
Author: DjalalxJay (https://sketchfab.com/djalalxjay)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/simple-satellite-low-poly-free-f23b484cda664f1cb91b4f62ea5ef8bf
Title: Simple Satellite Low Poly Free
*/

import * as THREE from 'three';
import React from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib'; // Correct import for GLTF types

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh;
    Object_5: THREE.Mesh;
    Object_6: THREE.Mesh;
    Object_8: THREE.Mesh;
    Object_10: THREE.Mesh;
    Object_12: THREE.Mesh;
    Object_14: THREE.Mesh;
    Object_16: THREE.Mesh;
    Object_18: THREE.Mesh;
    Object_19: THREE.Mesh;
    Object_21: THREE.Mesh;
    Object_22: THREE.Mesh;
    Object_24: THREE.Mesh;
    Object_26: THREE.Mesh;
    Object_28: THREE.Mesh;
    Object_29: THREE.Mesh;
    Object_31: THREE.Mesh;
    Object_33: THREE.Mesh;
    Object_35: THREE.Mesh;
    Object_37: THREE.Mesh;
    Object_39: THREE.Mesh;
    Object_41: THREE.Mesh;
    Object_43: THREE.Mesh;
    Object_45: THREE.Mesh;
    Object_47: THREE.Mesh;
    Object_49: THREE.Mesh;
    Object_51: THREE.Mesh;
    Object_53: THREE.Mesh;
    Object_55: THREE.Mesh;
    Object_56: THREE.Mesh;
  };
  materials: {
    Satellite: THREE.MeshStandardMaterial;
    Gold: THREE.MeshStandardMaterial;
    Satellite_2: THREE.MeshStandardMaterial;
    Packs: THREE.MeshStandardMaterial;
    Solar_Panel: THREE.MeshStandardMaterial;
  };
  animations: THREE.AnimationAction[]; // Use THREE.AnimationAction here
};

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/satellite.gltf') as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group rotation={[-1.755, 0.06, 2.589]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, 0, 0.186]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={[0.875, 0.883, 0.875]}>
            <mesh geometry={nodes.Object_4.geometry} material={materials.Satellite} />
            <mesh geometry={nodes.Object_5.geometry} material={materials.Gold} />
            <mesh geometry={nodes.Object_6.geometry} material={materials.Satellite_2} />
          </group>
          <group rotation={[0, 0, 0.137]} scale={0.075}>
            <mesh geometry={nodes.Object_18.geometry} material={materials.Satellite} />
            <mesh geometry={nodes.Object_19.geometry} material={materials.Gold} />
          </group>
          <group position={[0, 0, 2.294]} rotation={[0, 0, -0.402]} scale={0.075}>
            <mesh geometry={nodes.Object_21.geometry} material={materials.Satellite} />
            <mesh geometry={nodes.Object_22.geometry} material={materials.Gold} />
          </group>
          <group position={[0, 0, 3.53]} rotation={[0, 0, 0.995]} scale={0.06}>
            <mesh geometry={nodes.Object_28.geometry} material={materials.Satellite} />
            <mesh geometry={nodes.Object_29.geometry} material={materials.Gold} />
          </group>
          <group position={[0, 0, 2.575]}>
            <mesh geometry={nodes.Object_55.geometry} material={materials.Satellite} />
            <mesh geometry={nodes.Object_56.geometry} material={materials.Solar_Panel} />
          </group>
          <mesh geometry={nodes.Object_8.geometry} material={materials.Satellite} position={[0, 0, 1.395]} />
          <mesh geometry={nodes.Object_10.geometry} material={materials.Satellite} position={[0, 0, 1.781]} />
          <mesh geometry={nodes.Object_12.geometry} material={materials.Satellite} position={[0, 0, 0.519]} />
          <mesh geometry={nodes.Object_14.geometry} material={materials.Satellite} position={[0, 0, 1.584]} />
          <mesh geometry={nodes.Object_16.geometry} material={materials.Gold} position={[0, -0.018, 1.821]} rotation={[0, 0, 0.021]} />
          <mesh geometry={nodes.Object_24.geometry} material={materials.Packs} position={[0, 0, 2.699]} rotation={[0, 0, -0.481]} />
          <mesh geometry={nodes.Object_26.geometry} material={materials.Packs} position={[0, 0, 2.127]} />
          <mesh geometry={nodes.Object_31.geometry} material={materials.Satellite} position={[0, 0, 2.831]} rotation={[0, 0, -0.811]} />
          <mesh geometry={nodes.Object_33.geometry} material={materials.Packs} position={[0, 0, 3.04]} rotation={[0, 0, 1.475]} />
          <mesh geometry={nodes.Object_35.geometry} material={materials.Packs} position={[0, 0, 3.277]} rotation={[0, 0, 1.475]} />
          <mesh geometry={nodes.Object_37.geometry} material={materials.Gold} />
          <mesh geometry={nodes.Object_39.geometry} material={materials.Gold} position={[0, 0, 1.332]} />
          <mesh geometry={nodes.Object_41.geometry} material={materials.Gold} position={[0, 0, 2.78]} rotation={[0, 0, 1.397]} scale={0.803} />
          <mesh geometry={nodes.Object_43.geometry} material={materials.Satellite} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={1.465} />
          <mesh geometry={nodes.Object_45.geometry} material={materials.Satellite} rotation={[0, Math.PI / 2, 0]} />
          <mesh geometry={nodes.Object_47.geometry} material={materials.Satellite} position={[0, 0, -0.508]} rotation={[Math.PI / 2, Math.PI / 4, -Math.PI / 2]} />
          <mesh geometry={nodes.Object_49.geometry} material={materials.Satellite} position={[0, 0, -1.248]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} />
          <mesh geometry={nodes.Object_51.geometry} material={materials.Satellite} position={[0, 0, -1.237]} rotation={[Math.PI / 2, Math.PI / 4, -Math.PI]} />
          <mesh geometry={nodes.Object_53.geometry} material={materials.Satellite} position={[0, 0, -1.237]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/satellite.gltf');
